### ISSUE TITLE
Feature Request: Custom settings.json per config.

### ISSUE THREAD

**Issue by dschu012** [Farmith/D2RMIM#6]
I like to run my other boxes smaller and with less intensive graphics settings. It'd be nice if there was a way to temporarily replace the settings.json right before launching an instance and then recovering your original settings.json after it is launched.

**Comment by Farmith** [comment]
Will look into it, thank you for the idea!

**Comment by Farmith** [comment]
@dschu012 how do you perceive this to work? do you see it as something that you have a general override config, or something you want to set on a per-account basis?

**Comment by dschu012** [comment]
per account. basically i like my main box i play on to be `"Screen Resolution (Windowed)": "1920x900",` while my other instances to be something much smaller. ideally I could have like a `Box1.Settings.json`, `Box2.Settings.json`, etc... that you would just rename and put in `%userprofile%\Saved Games\Diablo II Resurrected` prior to launching.

**Comment by Farmith** [comment]
Ill look into enabling something like that in the coming release for you :) will probably be very basic like "Override json" checkbox or something that you can use, will leave the modification of the copied json file up to the discretion of the user for the time being. (I.e probably i copy the existing settings.json into the local folder 1x per account with account name as per your suggestion, and you can modify it before pressing launch in the UI, something in those lines.

**Comment by Farmith** [comment]
This is now in 1.6
