### ISSUE TITLE
After Patch not working good !!!

### ISSUE THREAD

**Issue by Greenapple2021** [Farmith/D2RMIM#8]
Hope to fix the same problem like old version.

after restart PC MultiInstanceManager not working anymore.

must be always like at old version remove all profiles and add news.

**Comment by Farmith** [comment]
could you be a little more specific please? which version are you having trouble with, which version worked better for you?

Also, there have been no updates to D2RMIM for a while now as i have been refactoring it into a huge new release in .NET 6.0 which will be coming out soon.

**Comment by Greenapple2021** [comment]
1.6.6

sob., 4 gru 2021, 13:04 użytkownik Farmith ***@***.***>
napisał:

**Comment by drDentist** [comment]
Refreshing not working for me anymore since patch,
only first acc works,
 rest in offline mode

**Comment by Greenapple2021** [comment]
Its true

sob., 4 gru 2021, 13:45 użytkownik drDentist ***@***.***>
napisał:

**Comment by Farmith** [comment]
drDentist, try going back to 1.6.4 while waiting for 2.0, there are a couple known issues in 1.6.6 that have been fixed in 2.0 but were'nt there in 1.6.4. Hope that helps

**Comment by Greenapple2021** [comment]
> drDentist, try going back to 1.6.4 while waiting for 2.0, there are a couple known issues in 1.6.6 that have been fixed in 2.0 but were'nt there in 1.6.4. Hope that helps

redownloaded 2.0 new version no multimanager launcher there, nothing happends

**Comment by drDentist** [comment]
Problem solved
AFTER UPDATE you can't use proxifier with D2R1.Exe,D2R2.exe and so on ANYMORE without updating them manually!!!!!
Just update all  your D2R execs and all works
